In [4]:
%load_ext autoreload
%autoreload 2
from NeuralNetwork import *

In [4]:
from NeuralNetwork import *
programConv = cl.Program(context, open('kernelsConv.cl').read()).build()
conv = Conv((5,5),4,0,(28,28,3),(2,2),sigmoid)

conv.allocateMemory(10)
ym1 = Tensor(np.random.randn(10,28,28,3))
Y = conv.forwardPropagate(ym1)

e = Tensor(Y.get())
conv.computeError(Y, e)
conv.computedb(e)
conv.computeGradients(ym1, e)

AttributeError: 'learningRule' was not found as a program info attribute or as a kernel name

In [ ]:
grads = conv.dw.get()

In [ ]:
conv.testGrads()

In [3]:
programConv = cl.Program(context, open('kernelsConv.cpp').read()).build()


In [4]:
%load_ext autoreload
from NeuralNetwork import *
programConv = cl.Program(context, open('kernelsConv.cpp').read()).build()
conv = Conv((5,5),4,0,(28,28,3),(2,2),sigmoid)

conv.allocateMemory(10)

ym1 = Tensor(np.random.randn(10,28,28,3))
Y = conv.forwardPropagate(ym1)
e = Tensor(Y.get())
conv.backwardPropagate(Y=Y,e=e, lrate=0)

print(conv.db.shape)
conv.db

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


KeyError: 'sigma'

In [ ]:
conv = Conv((2,2),10,0,(10,10,1),(1,1),sigmoid)
conv.allocateMemory(1)
conv.w.set(np.ones(conv.w.shape))
conv.b.set(np.ones(conv.b.shape))
conv.forwardPropagate(Tensor(np.ones((1,10,10,1))))
conv.v

[[[[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
   [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
   [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
   [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
   [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
   [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
   [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
   [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]]

  [[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
   [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
   [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
   [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
   [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
   [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
   [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
   [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]]

  [[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
   [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
   [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
   [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
   [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
   [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
   [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
   [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]]

  [[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
   [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
   [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
   [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
   [5. 5. 5. 5